name: Python package
on: [workflow_dispatch, push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]


    steps:

    - name: checkout repo
      uses: actions/checkout@v4
    - name: Set up Python 3.9 (32-bit)
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        architecture: 'x86'
    - name: Set up environment variables for Clang
      run: |
        echo CPLUS_INCLUDE_PATH=${{ runner.tool_cache }}/Python/3.9.13/x86/include > $GITHUB_ENV
        echo LIBRARY_PATH=${{ runner.tool_cache }}/Python/3.9.13/x86/libs >> $GITHUB_ENV

    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Check dirs
      run: |
        echo "Current directory: $(pwd)"
        echo "Listing root directory contents:"
        ls
        echo "getting python dirs"
        where python
    - name: Check python path
      run: |
        where *python*
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        py -V
        python -m pip install flake8 pytest
        python -m pip install -r requirements.txt
    - name: Setup MSVC Developer Command Prompt
      uses: TheMrMilchmann/setup-msvc-dev@v3.0.1
      with:
        arch: x86


    - name: Start Building
      run: |
        python -V
        python setup.py bdist_wheel
